---

kind: ConfigMap
apiVersion: v1
metadata:
  name: $APP_NAME-config
data:
  NODE_ENV: production
  CONTENTFUL_SPACE_ID: "$CONTENTFUL_SPACE_ID"
  CONTENTFUL_DELIVERY_API_KEY: "$CONTENTFUL_DELIVERY_API_KEY"
  SMTP_HOST: "$SMTP_HOST"
  SMTP_PORT: "$SMTP_PORT"
  SMTP_USER: "$SMTP_USER"
  SMTP_PASSWORD: "$SMTP_PASSWORD"
  EMAIL_SENDER: "$EMAIL_SENDER"
  EMAIL_REPLY_TO: "$EMAIL_REPLY_TO"
