export * from './consultation-layout';
export * from './digital-audit-layout';
export * from './digital-eco-layout';
export * from './event-page-layout';
export * from './gdpr-layout';
export * from './global-layout';
export * from './project-details-layout';
export * from './home-page-layout';
export * from './mkt-campaign-layout';
